esphomeyaml:
  name: gang
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: 'Inteno-EA3F'
  password: 'VMWIDUT3ANASBU'
  hostname: 'gang'
  domain: '.local'
  manual_ip:
    static_ip: 192.168.0.164
    gateway: 192.168.0.1
    subnet: 255.255.255.0

mqtt:
  broker: '192.168.0.105'
  username: 'rolf'
  password: 'b3aronSEmqtt'

# Enable logging
logger:

ota:

i2c:

# Sensors
binary_sensor:
  - platform: gpio
    pin: D7
    name: "Bevegelsessensor gang"
    device_class: motion

sensor:
  - platform: bme280
    temperature:
      name: "Temperatur gang"
      oversampling: 16x
    pressure:
      name: "Lufttrykk gang"
    humidity:
      name: "Luftfuktighet gang"
    address: 0x76
    update_interval: 10s
